### ISSUE TITLE
IMGUI Sample

### ISSUE THREAD

**Issue by v-mbelchior** [ab4d/Ab4d.SharpEngine.Samples#18]
Hello,

It would be great to have an IMGUI sample, mapping the input and rendering the IMGUI mesh.

**Comment by rokm** [comment]
Initial version of an ImGui example was added to `main` branch in 061173a, and there is (at the moment) identical version available in the `versions/2.1` branch. Let us know if the sample sufficiently demonstrates the aspects you had in mind, or should we extend it in any area.

**Comment by stephensmitchell** [comment]
Running the sample fails at line: 

https://github.com/ab4d/Ab4d.SharpEngine.Samples/blob/cd3f0571b45e440544655ec4bdf3cd2174d1e15e/Ab4d.SharpEngine.Samples.ImGui/ImGuiRenderingStep.cs#L516

Output:

`Unhandled exception. Ab4d.SharpEngine.Vulkan.VulkanException: vkAllocateDescriptorSets error: ErrorOutOfPoolMemory (-1000069000)
   at Ab4d.SharpEngine.Vulkan.VulkanDevice.CreateDescriptorSets(DescriptorSetLayout descriptorSetLayout, DescriptorPool descriptorPool, Int32 count, String name, Int32 nameStartIndex)
   at Ab4d.SharpEngine.Samples.ImGui.ImGuiRenderingStep.InitializeFontTextureResources(RenderingContext renderingContext) in \Ab4d.SharpEngine.Samples-main\Ab4d.SharpEngine.Samples.ImGui\ImGuiRenderingStep.cs:line 516
   at Ab4d.SharpEngine.Samples.ImGui.ImGuiRenderingStep.OnRun(RenderingContext renderingContext) in \Ab4d.SharpEngine.Samples-main\Ab4d.SharpEngine.Samples.ImGui\ImGuiRenderingStep.cs:line 84
   at Ab4d.SharpEngine.RenderingSteps.RenderingStep.Run(RenderingContext renderingContext)
   at Ab4d.SharpEngine.SceneView.??(RenderingContext ?)
   at Ab4d.SharpEngine.SceneView.Render(Boolean forceRender, Boolean forceUpdateAll, Boolean cleanup)
   at Ab4d.SharpEngine.Samples.ImGui.Program.<>c.<Main>b__15_1(Double _) in \Ab4d.SharpEngine.Samples-main\Ab4d.SharpEngine.Samples.ImGui\Program.cs:line 89
   at Silk.NET.Windowing.Internals.ViewImplementationBase.DoRender()
   at Silk.NET.Windowing.WindowExtensions.<>c__DisplayClass2_0.<Run>b__0()
   at Silk.NET.Windowing.Glfw.GlfwWindow.<RegisterCallbacks>b__93_3(WindowHandle* window)`
   
   How to fix this?
